apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-dso-training
spec:
  title: DSO Workshop
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/CYB3RV4D3R/devsecops-training
  content:
    image: docker.io/cpauley/dso-container:main
    files: github.com/CYB3RV4D3R/devsecops-training
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
